Reproducible builds (step by step guide)
ElrondNetwork/elrond-sdk-images pull request #6
Opened 2022-06-10 20:59 UTC by andreibancioiu

2022-09-19 14:06 UTC, andreibancioiu commented on scripts/build_contract_rust_within_docker.py
> +    HARDCODED_BUILD_DIRECTORY.mkdir()
The build is performed at this fixed location in the container.

2022-09-19 14:08 UTC, andreibancioiu commented on scripts/build_contract_rust_within_docker.py
> +def adjust_output_ownership(output_directory: Path, owner_id: int, group_id: int):
This is a mandatory step, since all files generated within Docker will be owned by `root`.

2022-09-19 16:47 UTC, andrei-marinica requested changes

2022-09-19 16:47 UTC, andrei-marinica commented on scripts/build_contract_rust_within_docker.py
> +    args = ["cargo", "run", "build", "--target=wasm32-unknown-unknown", "--release"]
Arguments `"--target=wasm32-unknown-unknown", "--release"` are not required, the meta crate places them automatically.

2022-09-20 06:29 UTC, andreibancioiu commented on scripts/build_contract_rust_within_docker.py
> +    args = ["cargo", "run", "build", "--target=wasm32-unknown-unknown", "--release"]
Thanks, fixed!

2022-09-20 09:00 UTC, ccorcoveanu approved these changes

2022-09-20 09:13 UTC, claudiu725 approved these changes

2022-09-20 09:24 UTC, andrei-marinica approved these changes

2022-09-20 09:45 UTC, merged